"""remember when the nickname was last changed

Revision ID: e4dd87e09e0c
Revises: 4aaa08733b1b
Create Date: 2026-10-02 10:31:27.958415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4dd87e09e0c'
down_revision: Union[str, Sequence[str], None] = '4aaa08733b1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('nickname_changed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'nickname_changed_at')
    # ### end Alembic commands ###
