"""one first sentence per story

Revision ID: 085be33de338
Revises: af6c8a9532c9
Create Date: 2026-09-21 18:08:42.972069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '085be33de338'
down_revision: Union[str, Sequence[str], None] = 'af6c8a9532c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_sentences_one_root_per_story', 'sentences', ['story_id'], unique=True, postgresql_where=sa.text('parent_id IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_sentences_one_root_per_story', table_name='sentences', postgresql_where=sa.text('parent_id IS NULL'))
    # ### end Alembic commands ###
