"""create initial tables

Revision ID: af6c8a9532c9
Revises: 
Create Date: 2026-09-17 14:18:15.653230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af6c8a9532c9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('provider_user_id', sa.String(length=255), nullable=False),
    sa.Column('nickname', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('nickname', name=op.f('uq_users_nickname')),
    sa.UniqueConstraint('provider', 'provider_user_id', name=op.f('uq_users_provider_provider_user_id'))
    )
    op.create_table('stories',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('creator_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("title ~ '\\S'", name=op.f('ck_stories_title_not_blank')),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], name=op.f('fk_stories_creator_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stories'))
    )
    op.create_index('ix_stories_created_at', 'stories', ['created_at'], unique=False)
    op.create_index('ix_stories_creator_id_created_at', 'stories', ['creator_id', 'created_at'], unique=False)
    op.create_table('sentences',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('story_id', sa.BigInteger(), nullable=False),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('author_id', sa.BigInteger(), nullable=False),
    sa.Column('content', sa.String(length=100), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=10), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("content ~ '\\S'", name=op.f('ck_sentences_content_not_blank')),
    sa.CheckConstraint("status IN ('active', 'folded', 'deleted', 'removed')", name=op.f('ck_sentences_status_valid')),
    sa.CheckConstraint('(parent_id IS NULL) = (depth = 0)', name=op.f('ck_sentences_root_iff_depth_zero')),
    sa.CheckConstraint('depth >= 0', name=op.f('ck_sentences_depth_non_negative')),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_sentences_author_id_users')),
    sa.ForeignKeyConstraint(['parent_id'], ['sentences.id'], name=op.f('fk_sentences_parent_id_sentences')),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], name=op.f('fk_sentences_story_id_stories')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sentences'))
    )
    op.create_index('ix_sentences_author_id_story_id_created_at', 'sentences', ['author_id', 'story_id', 'created_at'], unique=False)
    op.create_index('ix_sentences_parent_id', 'sentences', ['parent_id'], unique=False)
    op.create_index('ix_sentences_story_id_depth', 'sentences', ['story_id', 'depth'], unique=False)
    op.create_table('story_recommendations',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('story_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], name=op.f('fk_story_recommendations_story_id_stories')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_story_recommendations_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', 'story_id', name=op.f('pk_story_recommendations'))
    )
    op.create_index('ix_story_recommendations_story_id', 'story_recommendations', ['story_id'], unique=False)
    op.create_table('forum_posts',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('story_id', sa.BigInteger(), nullable=False),
    sa.Column('author_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('body', sa.String(length=5000), nullable=False),
    sa.Column('quoted_sentence_id', sa.BigInteger(), nullable=True),
    sa.Column('pin_slot', sa.SmallInteger(), nullable=True),
    sa.Column('status', sa.String(length=10), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'folded', 'deleted', 'removed')", name=op.f('ck_forum_posts_status_valid')),
    sa.CheckConstraint('pin_slot IN (1, 2)', name=op.f('ck_forum_posts_pin_slot_valid')),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_forum_posts_author_id_users')),
    sa.ForeignKeyConstraint(['quoted_sentence_id'], ['sentences.id'], name=op.f('fk_forum_posts_quoted_sentence_id_sentences')),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], name=op.f('fk_forum_posts_story_id_stories')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_forum_posts')),
    sa.UniqueConstraint('story_id', 'pin_slot', name=op.f('uq_forum_posts_story_id_pin_slot'))
    )
    op.create_index('ix_forum_posts_story_id_created_at', 'forum_posts', ['story_id', 'created_at'], unique=False)
    op.create_table('sentence_votes',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('sentence_id', sa.BigInteger(), nullable=False),
    sa.Column('value', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('value IN (1, -1)', name=op.f('ck_sentence_votes_value_valid')),
    sa.ForeignKeyConstraint(['sentence_id'], ['sentences.id'], name=op.f('fk_sentence_votes_sentence_id_sentences')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sentence_votes_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', 'sentence_id', name=op.f('pk_sentence_votes'))
    )
    op.create_index('ix_sentence_votes_sentence_id', 'sentence_votes', ['sentence_id'], unique=False)
    op.create_table('forum_comments',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('post_id', sa.BigInteger(), nullable=False),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('author_id', sa.BigInteger(), nullable=False),
    sa.Column('body', sa.String(length=1000), nullable=False),
    sa.Column('status', sa.String(length=10), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'folded', 'deleted', 'removed')", name=op.f('ck_forum_comments_status_valid')),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_forum_comments_author_id_users')),
    sa.ForeignKeyConstraint(['parent_id'], ['forum_comments.id'], name=op.f('fk_forum_comments_parent_id_forum_comments')),
    sa.ForeignKeyConstraint(['post_id'], ['forum_posts.id'], name=op.f('fk_forum_comments_post_id_forum_posts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_forum_comments'))
    )
    op.create_index('ix_forum_comments_post_id_created_at', 'forum_comments', ['post_id', 'created_at'], unique=False)
    op.create_table('forum_post_votes',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('post_id', sa.BigInteger(), nullable=False),
    sa.Column('value', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('value IN (1, -1)', name=op.f('ck_forum_post_votes_value_valid')),
    sa.ForeignKeyConstraint(['post_id'], ['forum_posts.id'], name=op.f('fk_forum_post_votes_post_id_forum_posts')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_forum_post_votes_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', 'post_id', name=op.f('pk_forum_post_votes'))
    )
    op.create_index('ix_forum_post_votes_post_id', 'forum_post_votes', ['post_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('reporter_id', sa.BigInteger(), nullable=False),
    sa.Column('sentence_id', sa.BigInteger(), nullable=True),
    sa.Column('post_id', sa.BigInteger(), nullable=True),
    sa.Column('comment_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('num_nonnulls(sentence_id, post_id, comment_id) = 1', name=op.f('ck_reports_one_target')),
    sa.ForeignKeyConstraint(['comment_id'], ['forum_comments.id'], name=op.f('fk_reports_comment_id_forum_comments')),
    sa.ForeignKeyConstraint(['post_id'], ['forum_posts.id'], name=op.f('fk_reports_post_id_forum_posts')),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], name=op.f('fk_reports_reporter_id_users')),
    sa.ForeignKeyConstraint(['sentence_id'], ['sentences.id'], name=op.f('fk_reports_sentence_id_sentences')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports')),
    sa.UniqueConstraint('comment_id', 'reporter_id', name=op.f('uq_reports_comment_id_reporter_id')),
    sa.UniqueConstraint('post_id', 'reporter_id', name=op.f('uq_reports_post_id_reporter_id')),
    sa.UniqueConstraint('sentence_id', 'reporter_id', name=op.f('uq_reports_sentence_id_reporter_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reports')
    op.drop_index('ix_forum_post_votes_post_id', table_name='forum_post_votes')
    op.drop_table('forum_post_votes')
    op.drop_index('ix_forum_comments_post_id_created_at', table_name='forum_comments')
    op.drop_table('forum_comments')
    op.drop_index('ix_sentence_votes_sentence_id', table_name='sentence_votes')
    op.drop_table('sentence_votes')
    op.drop_index('ix_forum_posts_story_id_created_at', table_name='forum_posts')
    op.drop_table('forum_posts')
    op.drop_index('ix_story_recommendations_story_id', table_name='story_recommendations')
    op.drop_table('story_recommendations')
    op.drop_index('ix_sentences_story_id_depth', table_name='sentences')
    op.drop_index('ix_sentences_parent_id', table_name='sentences')
    op.drop_index('ix_sentences_author_id_story_id_created_at', table_name='sentences')
    op.drop_table('sentences')
    op.drop_index('ix_stories_creator_id_created_at', table_name='stories')
    op.drop_index('ix_stories_created_at', table_name='stories')
    op.drop_table('stories')
    op.drop_table('users')
    # ### end Alembic commands ###
